### PR TITLE
ShushantKumar

### PR DESCRIPTION
**Pull request by NishantNITK**

### CODE REVIEW

**Comment by chinmaydd** [comment]
Fix merge conflicts please!

**Comment by NishantNITK** [comment]
Hi sir,
What does"fix merge conflict mean"?
And how to do it?
Nishant

**Comment by salman-bhai** [comment]
@NishantNITK Google how to "Sync a forked repository"

**Comment by salman-bhai** [comment]
@NishantNITK there's no use adding new files before resolving Merge Conflicts

**Pull request closed without merging**
